# Generated by Django 3.0.8 on 2020-07-26 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('fund_wallet', 'F_W'), ('send_money', 'S_M'), ('fund_card', 'F_C'), ('savings', '$')], max_length=35)),
                ('amount', models.FloatField(max_length=255)),
                ('origin', models.CharField(max_length=50)),
                ('receiver', models.CharField(blank=True, max_length=10, null=True)),
                ('nickel_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
