# Generated by Django 3.0.8 on 2020-07-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(default='YwtJMrpG90', max_length=10, unique=True),
        ),
    ]
