# Generated by Django 3.0.8 on 2020-08-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_auto_20200807_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(default='bT8SafkjKJ', max_length=10, unique=True),
        ),
    ]
